# Generated by Django 3.0.5 on 2020-06-14 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('video_file', models.FileField(upload_to='videos/%y/%m/%d/')),
                ('time_added', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
