# Generated by Django 3.0.5 on 2020-06-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200614_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_file', models.FileField(upload_to='Audios/%y/%m/%d/')),
                ('time_added', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'List of Audios',
            },
        ),
    ]
