# Generated by Django 3.0.5 on 2020-06-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
