# Generated by Django 3.0.5 on 2020-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20200702_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_img',
            field=models.ImageField(default=1, upload_to='Audio_pics/%y/%m/'),
            preserve_default=False,
        ),
    ]
