# Generated by Django 3.0.5 on 2020-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20200708_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
