# Generated by Django 3.0.5 on 2020-07-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20200710_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='disc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='disc',
            new_name='desc',
        ),
    ]
