# Generated by Django 3.0.5 on 2020-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20200710_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('desc', models.TextField(blank=True, null=True)),
                ('url_video', models.CharField(blank=True, max_length=2083, null=True)),
                ('time_added', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name_plural': 'List of popular videos',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='url_video',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
