# Generated by Django 3.0.5 on 2020-09-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_auto_20200904_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_img',
            field=models.ImageField(upload_to='Audio_pics'),
        ),
    ]
