# Generated by Django 3.0.5 on 2020-10-14 03:16

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_auto_20200904_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('url_vid', embed_video.fields.EmbedVideoField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Trending Videos',
            },
        ),
    ]
