# Generated by Django 3.0.5 on 2020-10-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_trendingvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingvideo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
