# Generated by Django 3.0.5 on 2020-05-02 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='comment_pic/%y/%m/%d/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='comment',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 3, 5, 33, 537581, tzinfo=utc)),
        ),
    ]
