# Generated by Django 3.0.5 on 2020-05-06 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200506_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 3, 21, 36, 290957, tzinfo=utc)),
        ),
    ]
