# Generated by Django 3.0.5 on 2020-05-10 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200506_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 17, 48, 31, 333014, tzinfo=utc)),
        ),
    ]
