# Generated by Django 3.0.5 on 2020-05-14 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200510_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 1, 2, 54, 101613, tzinfo=utc)),
        ),
    ]
