# Generated by Django 3.0.5 on 2020-06-18 00:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200614_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Logo_pics')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Logo Image',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 18, 0, 14, 32, 685507, tzinfo=utc)),
        ),
    ]
