# Generated by Django 3.0.5 on 2020-06-18 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200618_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 18, 0, 18, 50, 246851, tzinfo=utc)),
        ),
    ]
