# Generated by Django 3.0.5 on 2020-07-10 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200629_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 10, 14, 45, 11, 7355, tzinfo=utc)),
        ),
    ]
