# Generated by Django 3.0.5 on 2020-09-04 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200710_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 4, 1, 2, 7, 316871, tzinfo=utc)),
        ),
    ]
