# Generated by Django 3.0.5 on 2020-09-04 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200904_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 4, 1, 49, 34, 36039, tzinfo=utc)),
        ),
    ]
