# Generated by Django 3.0.5 on 2020-09-04 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200904_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 4, 9, 6, 2, 266088, tzinfo=utc)),
        ),
    ]
