# Generated by Django 3.0.5 on 2020-09-04 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200904_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 9, 13, 47, 534255, tzinfo=utc)),
        ),
    ]
