# Generated by Django 3.0.5 on 2020-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_sidebar_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
