# Generated by Django 3.0.5 on 2020-09-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200911_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'verbose_name_plural': 'SideBar Greetings'},
        ),
        migrations.AddField(
            model_name='sidebar',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Publish')], default='D', max_length=10),
        ),
    ]
