# Generated by Django 3.0.5 on 2020-09-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200920_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
