# Generated by Django 3.0.5 on 2020-09-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200920_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_url',
            new_name='url_video',
        ),
    ]
