# Generated by Django 3.0.5 on 2020-09-25 03:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200920_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=2083, null=True),
        ),
    ]
