# Generated by Django 3.0.5 on 2020-09-26 01:41

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20200925_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
