# Generated by Django 3.0.5 on 2020-10-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_store', '0002_delete_amazoncarousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('img', models.ImageField(upload_to='amazon_store')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', models.CharField(max_length=20)),
                ('label', models.CharField(choices=[('N', 'New'), ('R', 'Recent'), ('O', 'Old')], default='N', max_length=20)),
                ('category', models.CharField(choices=[('E', 'Electronics'), ('C', 'Computers'), ('SH', 'Smart Home'), ('A', 'Arts & Crafts'), ('AT', 'Automotive'), ('B', 'Baby'), ('BP', 'Beauty & personal care'), ('W', "Women's Fashion"), ('M', "Men's Fashion"), ('G', "Girl's Fashion"), ('H', 'Health and Household'), ('HK', 'Home and Kitchen'), ('I', 'Industrial and Scientific'), ('L', 'Luggage'), ('MT', 'Movies & Television'), ('P', 'Pet suppies'), ('S', 'Software'), ('SO', 'Sports and Outdoor'), ('THM', 'Tools & Home Improvement'), ('TG', 'Toys and Games'), ('VG', 'Video Games'), ('BF', "Boy's Fashion")], default='E', max_length=20)),
            ],
        ),
    ]
