# Generated by Django 3.0.5 on 2020-10-17 14:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_store', '0003_amazonstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonstore',
            options={'verbose_name_plural': 'Amazon Store'},
        ),
        migrations.AlterField(
            model_name='amazonstore',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
