# Generated by Django 3.0.5 on 2020-10-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_store', '0004_auto_20201017_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonstore',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amazonstore',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='amazonstore',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amazonstore',
            name='img',
            field=models.ImageField(height_field='height_field', upload_to='amazon_store', width_field='width_field'),
        ),
    ]
