# Generated by Django 3.0.5 on 2020-10-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_store', '0005_auto_20201017_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonstore',
            name='author',
        ),
        migrations.AddField(
            model_name='amazonstore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amazonstore',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
