# Generated by Django 3.0.5 on 2020-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_store', '0006_auto_20201017_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonstore',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonstore',
            name='label',
            field=models.CharField(choices=[('N', 'primary'), ('R', 'warning'), ('O', 'secondary')], default='N', max_length=20),
        ),
    ]
