# Generated by Django 3.0.5 on 2020-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_store', '0007_auto_20201017_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonstore',
            name='amazon_affiliate_link',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
