# Generated by Django 3.0.5 on 2020-10-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_store', '0008_amazonstore_amazon_affiliate_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonstore',
            name='amazon_affiliate_link',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='amazonstore',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='amazonstore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
