# Generated by Django 3.0.5 on 2020-05-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.AddField(
            model_name='reaction',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
