# Generated by Django 3.0.5 on 2020-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0004_auto_20200520_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name_plural': 'Documentation of Reactions'},
        ),
        migrations.AddField(
            model_name='reaction',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, null=True),
        ),
    ]
