# Generated by Django 3.0.5 on 2020-05-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'History/documentation of visited pages'},
        ),
    ]
